CREATE TABLE [REF_Manual].[Manuchar_Locations] (

	[LocationName] varchar(8000) NULL, 
	[LocationCode] varchar(8000) NULL, 
	[SiteName] varchar(8000) NULL, 
	[CompanyCode] varchar(8000) NULL, 
	[FirstUseDate] date NULL, 
	[Status] varchar(8000) NULL, 
	[LocationType] varchar(8000) NULL, 
	[LocationTypeCode] varchar(8000) NULL, 
	[LocationPropertyType] varchar(8000) NULL, 
	[IsBonded] bit NULL, 
	[Latitude] decimal(38,12) NULL, 
	[Longitude] decimal(38,12) NULL, 
	[LocationSize] decimal(20,2) NULL, 
	[StorageType] varchar(8000) NULL, 
	[DryStorageCapacity] decimal(20,2) NULL, 
	[LiquidStorageCapacity] decimal(20,2) NULL, 
	[ExpiryConcessionDate] date NULL, 
	[Licenses] varchar(8000) NULL, 
	[DateLatestReviewLocalTeam] date NULL, 
	[ModifiedBy] varchar(8000) NULL, 
	[ModifiedDateTime] datetime2(6) NULL, 
	[ApprovalState] varchar(8000) NULL, 
	[CompanyName] varchar(8000) NULL, 
	[CompanyRegion1] varchar(8000) NULL, 
	[CompanyRegion2] varchar(8000) NULL, 
	[LocationID] int NULL, 
	[LoadDateTime] datetime2(6) NULL
);