CREATE TABLE [MonaOnPrem].[TD030E2__ODS] (

	[LocalAdjustmentsDetailsID] int NULL, 
	[ConsoID] int NULL, 
	[LocalAdjustmentsHeaderID] int NULL, 
	[Sequence] int NULL, 
	[AccountID] int NULL, 
	[CurrCode] varchar(8000) NULL, 
	[Amount] decimal(24,6) NULL, 
	[ModifiedDate] datetime2(3) NULL, 
	[ModifiedBy] varchar(8000) NULL, 
	[ModifiedOrigin] varchar(8000) NULL, 
	[ODSConsoYear] smallint NULL, 
	[ODSConsoMonth] int NULL, 
	[ODSKey] varchar(61) NULL, 
	[ODSVersion] varchar(8000) NULL, 
	[ODSRecordStatus] varchar(8000) NULL, 
	[ODSActive] varchar(8000) NULL, 
	[ODSDeleted] varchar(8000) NULL, 
	[ODSModifiedOn] varchar(8000) NULL, 
	[ODSModifiedBy] varchar(8000) NULL, 
	[ODSIngestionDate] varchar(8000) NULL, 
	[ODSStartDate] varchar(8000) NULL, 
	[ODSEndDate] varchar(8000) NULL, 
	[ODSHash] varchar(8000) NULL
);