CREATE TABLE [MonaOnPrem].[TD030E0__ODS] (

	[LocalAdjustmentsHeaderID] int NULL, 
	[ConsoID] int NULL, 
	[CompanyID] int NULL, 
	[JournalTypeID] int NULL, 
	[CurrCode] varchar(8000) NULL, 
	[JournalEntry] bigint NULL, 
	[JournalText] varchar(8000) NULL, 
	[Behaviour] int NULL, 
	[MinorityFlag] bit NULL, 
	[AssociatedJournalTypeID] int NULL, 
	[CurrencyFlag] char(1) NULL, 
	[Status] bit NULL, 
	[CreationUserLogin] varchar(8000) NULL, 
	[CreationDate] datetime2(3) NULL, 
	[ModificationUserLogin] varchar(8000) NULL, 
	[ModificationDate] datetime2(3) NULL, 
	[FlagCarryForward] bit NULL, 
	[CarryForwardDate] datetime2(3) NULL, 
	[ODSConsoYear] smallint NULL, 
	[ODSConsoMonth] int NULL, 
	[ODSKey] varchar(61) NULL, 
	[ODSVersion] varchar(8000) NULL, 
	[ODSRecordStatus] varchar(8000) NULL, 
	[ODSActive] varchar(8000) NULL, 
	[ODSDeleted] varchar(8000) NULL, 
	[ODSModifiedOn] varchar(8000) NULL, 
	[ODSModifiedBy] varchar(8000) NULL, 
	[ODSIngestionDate] varchar(8000) NULL, 
	[ODSStartDate] varchar(8000) NULL, 
	[ODSEndDate] varchar(8000) NULL, 
	[ODSHash] varchar(8000) NULL
);