CREATE TABLE [MonaOnPrem].[TD055C2__ODS] (

	[ConsolidatedAmountDimID] bigint NULL, 
	[ConsoID] int NULL, 
	[ConsolidatedAmountID] bigint NULL, 
	[DimensionGroupID] int NULL, 
	[Dim1DetailID] int NULL, 
	[Dim2DetailID] int NULL, 
	[Dim3DetailID] int NULL, 
	[Amount] decimal(24,6) NULL, 
	[TransactionAmount] decimal(24,6) NULL, 
	[ODSConsoYear] smallint NULL, 
	[ODSConsoMonth] int NULL, 
	[ODSKey] varchar(61) NULL, 
	[ODSVersion] varchar(8000) NULL, 
	[ODSRecordStatus] varchar(8000) NULL, 
	[ODSActive] varchar(8000) NULL, 
	[ODSDeleted] varchar(8000) NULL, 
	[ODSModifiedOn] varchar(8000) NULL, 
	[ODSModifiedBy] varchar(8000) NULL, 
	[ODSIngestionDate] varchar(8000) NULL, 
	[ODSStartDate] varchar(8000) NULL, 
	[ODSEndDate] varchar(8000) NULL, 
	[ODSHash] varchar(8000) NULL
);