CREATE TABLE [MonaOnPrem].[V_DIMENSIONDETAIL__STG] (

	[DimensionDetailID] int NULL, 
	[DimensionID] int NULL, 
	[DimensionDetailCode] varchar(8000) NULL, 
	[DimensionDetailDescriptionID] int NULL, 
	[ParentDimensionDetailID] int NULL, 
	[ParentDimensionDetailCode] varchar(8000) NULL, 
	[ConsoID] int NULL, 
	[DimensionCode] varchar(8000) NULL, 
	[DimensionDescription] varchar(8000) NULL, 
	[DimensionDetailDescription] varchar(8000) NULL, 
	[ChildCount] int NULL, 
	[Level] smallint NULL, 
	[OrderNbr] int NULL, 
	[Type] char(1) NULL, 
	[ODSConsoYear] smallint NULL, 
	[ODSConsoMonth] int NULL, 
	[ODSKey] varchar(61) NULL, 
	[ODSVersion] varchar(8000) NULL, 
	[ODSRecordStatus] varchar(8000) NULL, 
	[ODSActive] varchar(8000) NULL, 
	[ODSDeleted] varchar(8000) NULL, 
	[ODSModifiedOn] varchar(8000) NULL, 
	[ODSModifiedBy] varchar(8000) NULL, 
	[ODSIngestionDate] varchar(8000) NULL, 
	[ODSStartDate] varchar(8000) NULL, 
	[ODSEndDate] varchar(8000) NULL, 
	[ODSHash] varchar(8000) NULL
);