CREATE TABLE [MonaOnPrem].[V_DIMENSIONGROUP__ODS] (

	[DimensionGroupID] int NULL, 
	[ConsoID] int NULL, 
	[DimensionGroupCode] varchar(8000) NULL, 
	[DimensionGroupName] varchar(8000) NULL, 
	[Dimension1ID] int NULL, 
	[Dimension2ID] int NULL, 
	[Dimension3ID] int NULL, 
	[Dimension1Code] varchar(8000) NULL, 
	[Dimension1Description] varchar(8000) NULL, 
	[Dimension2Code] varchar(8000) NULL, 
	[Dimension2Description] varchar(8000) NULL, 
	[Dimension3Code] varchar(8000) NULL, 
	[Dimension3Description] varchar(8000) NULL, 
	[Active] bit NULL, 
	[ODSConsoYear] smallint NULL, 
	[ODSConsoMonth] int NULL, 
	[ODSKey] varchar(61) NULL, 
	[ODSVersion] varchar(8000) NULL, 
	[ODSRecordStatus] varchar(8000) NULL, 
	[ODSActive] varchar(8000) NULL, 
	[ODSDeleted] varchar(8000) NULL, 
	[ODSModifiedOn] varchar(8000) NULL, 
	[ODSModifiedBy] varchar(8000) NULL, 
	[ODSIngestionDate] varchar(8000) NULL, 
	[ODSStartDate] varchar(8000) NULL, 
	[ODSEndDate] varchar(8000) NULL, 
	[ODSHash] varchar(8000) NULL
);