WITH sales_invoice_dynamics AS (
    SELECT
        dyn.bkey_sales_invoice_source,
        CAST(dyn.bkey_sales_invoice AS VARCHAR(100)) AS bkey_sales_invoice,
        dyn.bkey_source,
        CAST(dyn.sales_invoice_id AS VARCHAR(50)) AS sales_invoice_id,
        CAST(dyn.sales_invoice_customer_id AS VARCHAR(50)) AS sales_invoice_customer_id,
        CAST(dyn.sales_invoice_order_customer_id AS VARCHAR(50)) AS sales_invoice_order_customer_id,
        CAST(dyn.sales_invoice_company AS VARCHAR(50)) AS sales_invoice_company,
        CAST(sales_invoice_transactional_currency_code AS VARCHAR(50)) AS sales_invoice_transactional_currency_code,
        CAST(sales_invoice_group_currency_code AS VARCHAR(50)) AS sales_invoice_group_currency_code,
        CAST(sales_invoice_functional_currency_code AS VARCHAR(50)) AS sales_invoice_functional_currency_code,
        CAST(dyn.sales_invoice_date AS DATETIME2(6)) AS sales_invoice_date,
        CAST(dyn.sales_invoice_document_date AS DATETIME2(6)) AS sales_invoice_document_date,
        CAST(dyn.sales_invoice_due_date AS DATETIME2(6)) AS sales_invoice_due_date,
        CAST(dyn.sales_invoice_closure_date AS DATETIME2(6)) AS sales_invoice_closure_date,
        
        CAST(sales_invoice_amount_trans_cur AS DECIMAL(36, 6)) AS sales_invoice_amount_trans_cur,
        CAST(sales_invoice_amount_func_cur AS DECIMAL(36, 6)) AS sales_invoice_amount_func_cur,
        CAST(sales_invoice_amount_group_cur_conso_eom AS DECIMAL(36, 6)) AS sales_invoice_amount_group_cur_conso_eom,
        CAST(sales_invoice_amount_group_cur_conso_avg AS DECIMAL(36, 6)) AS sales_invoice_amount_group_cur_conso_avg,
        CAST(sales_invoice_amount_group_cur_oanda_eod AS DECIMAL(36, 6)) AS sales_invoice_amount_group_cur_oanda_eod,

        CAST(sales_invoice_open_amount_trans_cur AS DECIMAL(36, 6)) AS sales_invoice_open_amount_trans_cur,
        CAST(sales_invoice_open_amount_func_cur AS DECIMAL(36, 6)) AS sales_invoice_open_amount_func_cur,
        CAST(sales_invoice_open_amount_group_cur_conso_eom AS DECIMAL(36, 6)) AS sales_invoice_open_amount_group_cur_conso_eom,
        CAST(sales_invoice_open_amount_group_cur_conso_avg AS DECIMAL(36, 6)) AS sales_invoice_open_amount_group_cur_conso_avg,
        CAST(sales_invoice_open_amount_group_cur_oanda_eod AS DECIMAL(36, 6)) AS sales_invoice_open_amount_group_cur_oanda_eod, 

        CAST(sales_invoice_settled_amount_trans_cur AS DECIMAL(36, 6)) AS sales_invoice_settled_amount_trans_cur,
        CAST(sales_invoice_settled_amount_func_cur AS DECIMAL(36, 6)) AS sales_invoice_settled_amount_func_cur,
        CAST(sales_invoice_settled_amount_group_cur_conso_eom AS DECIMAL(36, 6)) AS sales_invoice_settled_amount_group_cur_conso_eom,
        CAST(sales_invoice_settled_amount_group_cur_conso_avg AS DECIMAL(36, 6)) AS sales_invoice_settled_amount_group_cur_conso_avg,
        CAST(sales_invoice_settled_amount_group_cur_oanda_eod AS DECIMAL(36, 6)) AS sales_invoice_settled_amount_group_cur_oanda_eod,

        CAST(sales_invoice_group_cur_conso_eom_rate AS DECIMAL(36, 6)) AS sales_invoice_group_cur_conso_eom_rate,
        CAST(sales_invoice_group_cur_conso_avg_rate AS DECIMAL(36, 6)) AS sales_invoice_group_cur_conso_avg_rate,
        CAST(sales_invoice_func_cur_rate AS DECIMAL(36, 6)) AS sales_invoice_func_cur_rate,

        CAST(dyn.sales_invoice_name AS VARCHAR(50)) AS sales_invoice_name,
        CAST(dyn.sales_invoice_customer_vat AS VARCHAR(50)) AS sales_invoice_customer_vat,
        CAST(dyn.sales_invoice_destination_country AS VARCHAR(50)) AS sales_invoice_destination_country,
        CAST(dyn.sales_invoice_external_reference AS VARCHAR(50)) AS sales_invoice_external_reference,
        CAST(dyn.sales_invoice_payment_schedule AS VARCHAR(50)) AS sales_invoice_payment_schedule,
        CAST(dyn.sales_invoice_ledger_voucher AS VARCHAR(50)) AS sales_invoice_ledger_voucher,
        CAST(dyn.sales_invoice_order_value AS VARCHAR(50)) AS sales_invoice_order_value,
        CAST(sales_invoice_payment AS VARCHAR(50)) AS sales_invoice_payment,
        CAST(sales_invoice_txt AS VARCHAR(50)) AS sales_invoice_txt,
        CAST(sales_invoice_closed AS VARCHAR(50)) AS sales_invoice_closed,
        CAST(sales_invoice_payment_reference AS VARCHAR(50)) AS sales_invoice_payment_reference,
        CAST(sales_invoice_paymtermid AS VARCHAR(50)) AS sales_invoice_paymtermid,
        CAST(sales_invoice_procenvalue AS VARCHAR) AS sales_invoice_procenvalue,
        CAST(sales_invoice_coscenvalue AS VARCHAR) AS sales_invoice_coscenvalue,
        CAST(sales_invoice_logistic_id AS VARCHAR) AS sales_invoice_logistic_id,
        CAST(sales_invoice_ledger_account AS VARCHAR) AS sales_invoice_ledger_account,
        CAST(sales_invoice_industry_code AS VARCHAR) AS sales_invoice_industry_code,
        CAST(sales_invoice_invent_location AS VARCHAR) AS sales_invoice_invent_location,
        CAST(sales_invoice_site_id AS VARCHAR) AS sales_invoice_site_id,
        CAST(dyn.sales_invoice_shipping_date AS DATETIME2(6)) AS sales_invoice_shipping_date,

        valid_from,
        valid_to,
        is_current
    FROM {{ ref('sales_invoice_dynamics') }} dyn
),

stg_sales_invoice AS (
    SELECT
        bkey_sales_invoice_source,
        CAST(bkey_sales_invoice AS VARCHAR(100)) AS bkey_sales_invoice,
        bkey_source,
        CAST(sales_invoice_id AS VARCHAR(50)) AS sales_invoice_id,
        CAST(sales_invoice_customer_id AS VARCHAR(50)) AS sales_invoice_customer_id,
        CAST(sales_invoice_order_customer_id AS VARCHAR(50)) AS sales_invoice_order_customer_id,
        CAST(sales_invoice_company AS VARCHAR(50)) AS sales_invoice_company,
        CAST(sales_invoice_transactional_currency_code AS VARCHAR(50)) AS sales_invoice_transactional_currency_code,
        CAST(sales_invoice_group_currency_code AS VARCHAR(50)) AS sales_invoice_group_currency_code,
        CAST(sales_invoice_functional_currency_code AS VARCHAR(50)) AS sales_invoice_functional_currency_code,
        CONVERT(DATETIME2(6), CONVERT(VARCHAR, sales_invoice_date), 103) AS sales_invoice_date,
        CONVERT(DATETIME2(6), CONVERT(VARCHAR, sales_invoice_document_date), 103) AS sales_invoice_document_date,
        CONVERT(DATETIME2(6), CONVERT(VARCHAR, sales_invoice_due_date), 103) AS sales_invoice_due_date,
        CONVERT(DATETIME2(6), CONVERT(VARCHAR, sales_invoice_closure_date), 103) AS sales_invoice_closure_date,
        
        NULL AS sales_invoice_amount_trans_cur,
        NULL AS sales_invoice_amount_func_cur,
        NULL AS sales_invoice_amount_group_cur_conso_eom,
        NULL AS sales_invoice_amount_group_cur_conso_avg,
        NULL AS sales_invoice_amount_group_cur_oanda_eod,

        NULL AS sales_invoice_open_amount_trans_cur,
        NULL AS sales_invoice_open_amount_func_cur,
        NULL AS sales_invoice_open_amount_group_cur_conso_eom,
        NULL AS sales_invoice_open_amount_group_cur_conso_avg,
        NULL AS sales_invoice_open_amount_group_cur_oanda_eod, 

        NULL AS sales_invoice_settled_amount_trans_cur,
        NULL AS sales_invoice_settled_amount_func_cur,
        NULL AS sales_invoice_settled_amount_group_cur_conso_eom,
        NULL AS sales_invoice_settled_amount_group_cur_conso_avg,
        NULL AS sales_invoice_settled_amount_group_cur_oanda_eod,

        CAST(sales_invoice_group_cur_conso_eom_rate AS DECIMAL(36, 6)) AS sales_invoice_group_cur_conso_eom_rate,
        CAST(sales_invoice_group_cur_conso_avg_rate AS DECIMAL(36, 6)) AS sales_invoice_group_cur_conso_avg_rate,
        CAST(sales_invoice_func_cur_rate AS DECIMAL(36, 6)) AS sales_invoice_func_cur_rate,

        CAST(sales_invoice_name AS VARCHAR(50)) AS sales_invoice_name,
        CAST(sales_invoice_customer_vat AS VARCHAR(50)) AS sales_invoice_customer_vat,
        CAST(sales_invoice_destination_country AS VARCHAR(50)) AS sales_invoice_destination_country,
        CAST(sales_invoice_external_reference AS VARCHAR(50)) AS sales_invoice_external_reference,
        CAST(sales_invoice_payment_schedule AS VARCHAR(50)) AS sales_invoice_payment_schedule,
        CAST(sales_invoice_ledger_voucher AS VARCHAR(50)) AS sales_invoice_ledger_voucher,
        CAST(sales_invoice_order_value AS VARCHAR(50)) AS sales_invoice_order_value,
        CAST(sales_invoice_payment AS VARCHAR(50)) AS sales_invoice_payment,
        CAST(sales_invoice_txt AS VARCHAR(50)) AS sales_invoice_txt,
        CAST(sales_invoice_closed AS VARCHAR(50)) AS sales_invoice_closed,
        CAST(sales_invoice_payment_reference AS VARCHAR(50)) AS sales_invoice_payment_reference,
        CAST(sales_invoice_paymtermid AS VARCHAR(50)) AS sales_invoice_paymtermid,
        CAST(sales_invoice_procenvalue AS VARCHAR) AS sales_invoice_procenvalue,
        CAST(sales_invoice_coscenvalue AS VARCHAR) AS sales_invoice_coscenvalue,
        CAST(sales_invoice_logistic_id AS VARCHAR) AS sales_invoice_logistic_id,
        CAST(sales_invoice_ledger_account AS VARCHAR) AS sales_invoice_ledger_account,
        CAST(sales_invoice_industry_code AS VARCHAR) AS sales_invoice_industry_code,
        CAST(sales_invoice_invent_location AS VARCHAR) AS sales_invoice_invent_location,
        CAST(sales_invoice_site_id AS VARCHAR) AS sales_invoice_site_id,
        NULL AS sales_invoice_shipping_date,
        valid_from,
        valid_to,
        is_current
    FROM {{ ref('sales_invoice_stg_sales') }}
),

stg_ar_invoice AS (
    SELECT
        bkey_sales_invoice_source,
        CAST(bkey_sales_invoice AS VARCHAR(50)) AS bkey_sales_invoice,
        bkey_source,
        CAST(sales_invoice_id AS VARCHAR(50)) AS sales_invoice_id,
        CAST(sales_invoice_customer_id AS VARCHAR(50)) AS sales_invoice_customer_id,
        CAST(sales_invoice_order_customer_id AS VARCHAR(50)) AS sales_invoice_order_customer_id,
        CAST(sales_invoice_company AS VARCHAR(50)) AS sales_invoice_company,
        CAST(sales_invoice_transactional_currency_code AS VARCHAR(50)) AS sales_invoice_transactional_currency_code,
        CAST(sales_invoice_group_currency_code AS VARCHAR(50)) AS sales_invoice_group_currency_code,
        CAST(sales_invoice_functional_currency_code AS VARCHAR(50)) AS sales_invoice_functional_currency_code,
        CONVERT(DATETIME2(6), CONVERT(VARCHAR, sales_invoice_date), 103) AS sales_invoice_date,
        CONVERT(DATETIME2(6), CONVERT(VARCHAR, sales_invoice_document_date), 103) AS sales_invoice_document_date,
        CONVERT(DATETIME2(6), CONVERT(VARCHAR, sales_invoice_due_date), 103) AS sales_invoice_due_date,
        CONVERT(DATETIME2(6), CONVERT(VARCHAR, sales_invoice_closure_date), 103) AS sales_invoice_closure_date,
        
        CAST(sales_invoice_amount_trans_cur AS DECIMAL(36, 6)) AS sales_invoice_amount_trans_cur,
        CAST(sales_invoice_amount_func_cur AS DECIMAL(36, 6)) AS sales_invoice_amount_func_cur,
        CAST(sales_invoice_amount_group_cur_conso_eom AS DECIMAL(36, 6)) AS sales_invoice_amount_group_cur_conso_eom,
        CAST(sales_invoice_amount_group_cur_conso_avg AS DECIMAL(36, 6)) AS sales_invoice_amount_group_cur_conso_avg,
        CAST(sales_invoice_amount_group_cur_oanda_eod AS DECIMAL(36, 6)) AS sales_invoice_amount_group_cur_oanda_eod,

        CAST(sales_invoice_open_amount_trans_cur AS DECIMAL(36, 6)) AS sales_invoice_open_amount_trans_cur,
        CAST(sales_invoice_open_amount_func_cur AS DECIMAL(36, 6)) AS sales_invoice_open_amount_func_cur,
        CAST(sales_invoice_open_amount_group_cur_conso_eom AS DECIMAL(36, 6)) AS sales_invoice_open_amount_group_cur_conso_eom,
        CAST(sales_invoice_open_amount_group_cur_conso_avg AS DECIMAL(36, 6)) AS sales_invoice_open_amount_group_cur_conso_avg,
        CAST(sales_invoice_open_amount_group_cur_oanda_eod AS DECIMAL(36, 6)) AS sales_invoice_open_amount_group_cur_oanda_eod, 

        CAST(sales_invoice_settled_amount_trans_cur AS DECIMAL(36, 6)) AS sales_invoice_settled_amount_trans_cur,
        CAST(sales_invoice_settled_amount_func_cur AS DECIMAL(36, 6)) AS sales_invoice_settled_amount_func_cur,
        CAST(sales_invoice_settled_amount_group_cur_conso_eom AS DECIMAL(36, 6)) AS sales_invoice_settled_amount_group_cur_conso_eom,
        CAST(sales_invoice_settled_amount_group_cur_conso_avg AS DECIMAL(36, 6)) AS sales_invoice_settled_amount_group_cur_conso_avg,
        CAST(sales_invoice_settled_amount_group_cur_oanda_eod AS DECIMAL(36, 6)) AS sales_invoice_settled_amount_group_cur_oanda_eod,

        CAST(sales_invoice_group_cur_conso_eom_rate AS DECIMAL(36, 6)) AS sales_invoice_group_cur_conso_eom_rate,
        CAST(sales_invoice_group_cur_conso_avg_rate AS DECIMAL(36, 6)) AS sales_invoice_group_cur_conso_avg_rate,
        CAST(sales_invoice_func_cur_rate AS DECIMAL(36, 6)) AS sales_invoice_func_cur_rate,

        CAST(sales_invoice_name AS VARCHAR(50)) AS sales_invoice_name,
        CAST(sales_invoice_customer_vat AS VARCHAR(50)) AS sales_invoice_customer_vat,
        CAST(sales_invoice_destination_country AS VARCHAR(50)) AS sales_invoice_destination_country,
        CAST(sales_invoice_external_reference AS VARCHAR(50)) AS sales_invoice_external_reference,
        CAST(sales_invoice_payment_schedule AS VARCHAR(50)) AS sales_invoice_payment_schedule,
        CAST(sales_invoice_ledger_voucher AS VARCHAR(50)) AS sales_invoice_ledger_voucher,
        CAST(sales_invoice_order_value AS VARCHAR(50)) AS sales_invoice_order_value,
        CAST(sales_invoice_payment AS VARCHAR(50)) AS sales_invoice_payment,
        CAST(sales_invoice_txt AS VARCHAR(50)) AS sales_invoice_txt,
        CAST(sales_invoice_closed AS VARCHAR(50)) AS sales_invoice_closed,
        CAST(sales_invoice_payment_reference AS VARCHAR(50)) AS sales_invoice_payment_reference,
        CAST(sales_invoice_paymtermid AS VARCHAR(50)) AS sales_invoice_paymtermid,
        CAST(sales_invoice_procenvalue AS VARCHAR) AS sales_invoice_procenvalue,
        CAST(sales_invoice_coscenvalue AS VARCHAR) AS sales_invoice_coscenvalue,
        CAST(sales_invoice_logistic_id AS VARCHAR) AS sales_invoice_logistic_id,
        CAST(sales_invoice_ledger_account AS VARCHAR) AS sales_invoice_ledger_account,
        CAST(sales_invoice_industry_code AS VARCHAR) AS sales_invoice_industry_code,
        CAST(sales_invoice_invent_location AS VARCHAR) AS sales_invoice_invent_location,
        CAST(sales_invoice_site_id AS VARCHAR) AS sales_invoice_site_id,
        NULL AS sales_invoice_shipping_date,
        valid_from,
        valid_to,
        is_current
    FROM {{ ref('sales_invoice_stg_ar') }}
)

SELECT * FROM sales_invoice_dynamics
UNION ALL
SELECT * FROM stg_sales_invoice
UNION ALL
SELECT * FROM stg_ar_invoice
