CREATE TABLE [REF_SHP].[MLocations_STG] (

	[Site_Id] varchar(10) NOT NULL, 
	[Site_code] varchar(50) NOT NULL, 
	[Site_name] varchar(250) NULL, 
	[Site_phoneNb] varchar(250) NULL, 
	[Site_adress] varchar(250) NULL, 
	[Site_zip] varchar(250) NULL, 
	[Site_city] varchar(250) NULL, 
	[Site_latitude] varchar(250) NULL, 
	[Site_longitude] varchar(250) NULL, 
	[Site_landsurface] varchar(250) NULL, 
	[Site_generalmail] varchar(250) NULL, 
	[Site_environment_responsible] varchar(250) NULL, 
	[Site_quality_responsible] varchar(250) NULL, 
	[Site_HR_responsible] varchar(250) NULL, 
	[Site_AuditInternal_responsible] varchar(250) NULL, 
	[Site_firstuse] datetime2(6) NULL, 
	[Site_lastReview] datetime2(6) NULL, 
	[Site_googlemaps] varchar(250) NULL, 
	[Site_countrycode] varchar(250) NULL, 
	[Site_country] varchar(250) NULL, 
	[Site_main_activity] varchar(250) NULL, 
	[Site_property_type] varchar(250) NULL, 
	[Site_status] varchar(250) NULL, 
	[Site_OwnendBy] varchar(250) NULL, 
	[Site_Bonded] varchar(250) NULL, 
	[Company_code] varchar(50) NOT NULL, 
	[Company_name] varchar(250) NULL, 
	[Company_region1] varchar(250) NULL, 
	[Company_region2] varchar(250) NULL, 
	[RowModifiedOn] datetime2(6) NULL, 
	[RowModifiedBy] varchar(100) NULL, 
	[ODSHash] varbinary(16) NULL, 
	[ODSKey] varchar(250) NULL, 
	[ODSVersion] int NULL, 
	[ODSChanged] varchar(3) NULL
);