CREATE TABLE [Test].[V_DATA_CONSO] (

	[ConsoID] int NULL, 
	[ConsolidatedAmountID] bigint NULL, 
	[ConsoCode] char(12) NULL, 
	[CompanyCode] varchar(8000) NULL, 
	[JournalType] char(1) NULL, 
	[JournalCategory] varchar(8000) NULL, 
	[JournalEntry] bigint NULL, 
	[JournalSequence] int NULL, 
	[Account] varchar(8000) NULL, 
	[PartnerCompanyCode] varchar(8000) NULL, 
	[CurrCode] varchar(8000) NULL, 
	[Amount] decimal(24,6) NULL, 
	[TransactionCurrCode] varchar(8000) NULL, 
	[TransactionAmount] decimal(24,6) NULL, 
	[CompanyID] int NULL, 
	[JournalTypeID] int NULL, 
	[AccountID] int NULL, 
	[PartnerCompanyID] int NULL, 
	[CustomerID] int NULL, 
	[MinorityFlag] bit NULL, 
	[ODSConsoYear] smallint NULL, 
	[ODSConsoMonth] int NULL, 
	[ODSKey] varchar(61) NULL, 
	[ODSVersion] varchar(8000) NULL, 
	[ODSRecordStatus] varchar(8000) NULL, 
	[ODSActive] varchar(8000) NULL, 
	[ODSDeleted] varchar(8000) NULL, 
	[ODSModifiedOn] varchar(8000) NULL, 
	[ODSModifiedBy] varchar(8000) NULL, 
	[ODSIngestionDate] varchar(8000) NULL, 
	[ODSStartDate] varchar(8000) NULL, 
	[ODSEndDate] varchar(8000) NULL, 
	[ODSHash] varchar(8000) NULL
);