CREATE TABLE [cds].[purchase_order_mtm] (

	[tkey_purchase_order] bigint NULL, 
	[bkey_purchase_order_source] varchar(8000) NULL, 
	[bkey_purchase_order] varchar(8000) NULL, 
	[bkey_source] varchar(3) NULL, 
	[purchase_order_payment_schedule] varchar(8000) NULL, 
	[purchase_order_payment] int NULL, 
	[purchase_order_dct_destination] int NULL, 
	[purchase_order_ecs_contract_status] int NULL, 
	[purchase_order_risk_trading_book_id] int NULL, 
	[purchase_order_created_date_time] datetime2(6) NULL, 
	[purchase_order_company] varchar(8000) NULL, 
	[purchase_order_partition] bigint NULL, 
	[purchase_order_order_account] varchar(8000) NULL, 
	[purchase_order_requester] int NULL, 
	[purchase_order_risk_trader] int NULL, 
	[purchase_order_worker_purchase_placer] int NULL, 
	[purchase_order_purchase_state] varchar(8000) NULL, 
	[purchase_order_ccs_closing_status] int NULL, 
	[purchase_order_ecs_trade_type] int NULL, 
	[purchase_order_purchase_type] int NULL, 
	[purchase_order_invoice_account] varchar(8000) NULL, 
	[purchase_order_accounting_date] int NULL, 
	[purchase_order_invoice_date] datetime2(6) NULL, 
	[purchase_order_amount_trans_cur] decimal(38,6) NULL, 
	[purchase_order_amount_func_cur] decimal(38,6) NULL, 
	[purchase_order_amount_group_cur_oanda_eod] int NULL, 
	[purchase_order_group_cur_oanda_eod_rate] numeric(38,12) NULL, 
	[purchase_order_func_cur_rate] decimal(38,6) NULL, 
	[purchase_order_transactional_currency_code] varchar(30) NULL, 
	[purchase_order_group_currency_code] varchar(3) NULL, 
	[purchase_order_functional_currency_code] int NULL, 
	[purchase_order_incoterm] varchar(8000) NULL, 
	[purchase_order_quantity] float NULL, 
	[purchase_order_quantity_mt] float NULL, 
	[purchase_order_uom] varchar(8000) NULL, 
	[valid_from] datetime2(6) NULL, 
	[valid_to] datetime2(6) NULL, 
	[is_current] int NOT NULL
);