CREATE TABLE [cds].[purchase_invoice_dynamics] (

	[bkey_purchase_invoice_source] varchar(8000) NULL, 
	[bkey_purchase_invoice] varchar(8000) NULL, 
	[bkey_source] varchar(8) NOT NULL, 
	[purchase_invoice_id] varchar(8000) NULL, 
	[purchase_invoice_supplier_id] varchar(8000) NULL, 
	[purchase_invoice_order_supplier_id] varchar(8000) NULL, 
	[purchase_invoice_company] varchar(8000) NULL, 
	[purchase_invoice_closure_date] datetime2(6) NULL, 
	[purchase_invoice_transactional_currency_code] varchar(8000) NULL, 
	[purchase_invoice_group_currency_code] varchar(3) NOT NULL, 
	[purchase_invoice_functional_currency_code] varchar(30) NULL, 
	[purchase_invoice_date] datetime2(6) NULL, 
	[purchase_invoice_document_date] datetime2(6) NULL, 
	[purchase_invoice_due_date] datetime2(6) NULL, 
	[purchase_invoice_amount_trans_cur] decimal(38,6) NULL, 
	[purchase_invoice_amount_func_cur] decimal(38,6) NULL, 
	[purchase_invoice_amount_group_cur_conso_eom] numeric(38,6) NULL, 
	[purchase_invoice_amount_group_cur_conso_avg] numeric(38,6) NULL, 
	[purchase_invoice_amount_group_cur_oanda_eod] int NULL, 
	[purchase_invoice_open_amount_trans_cur] decimal(38,6) NULL, 
	[purchase_invoice_open_amount_func_cur] decimal(38,6) NULL, 
	[purchase_invoice_open_amount_group_cur_conso_eom] numeric(38,6) NULL, 
	[purchase_invoice_open_amount_group_cur_conso_avg] numeric(38,6) NULL, 
	[purchase_invoice_open_amount_group_cur_oanda_eod] int NULL, 
	[purchase_invoice_settled_amount_trans_cur] decimal(18,2) NULL, 
	[purchase_invoice_settled_amount_func_cur] decimal(18,2) NULL, 
	[purchase_invoice_settled_amount_group_cur_conso_eom] numeric(38,6) NULL, 
	[purchase_invoice_settled_amount_group_cur_conso_avg] numeric(38,6) NULL, 
	[purchase_invoice_settled_amount_group_cur_oanda_eod] int NULL, 
	[purchase_invoice_group_cur_conso_eom_rate] numeric(38,12) NULL, 
	[purchase_invoice_group_cur_conso_avg_rate] numeric(38,12) NULL, 
	[purchase_invoice_func_cur_rate] decimal(38,6) NULL, 
	[purchase_invoice_ledger_voucher] varchar(8000) NULL, 
	[purchase_invoice_legal_number] varchar(8000) NULL, 
	[purchase_invoice_payment] varchar(8000) NULL, 
	[purchase_invoice_payment_schedule] varchar(8000) NULL, 
	[purchase_invoice_logistic_file_id] varchar(8000) NULL, 
	[purchase_invoice_tax_amount] decimal(38,6) NULL, 
	[purchase_invoice_purchase_id] varchar(8000) NULL, 
	[purchase_invoice_reporting_currency_exchange_rate] decimal(38,16) NULL, 
	[purchase_invoice_exchange_rate] decimal(38,16) NULL, 
	[purchase_invoice_quantity] decimal(38,6) NULL, 
	[purchase_invoice_internal_invoice_id] varchar(8000) NULL, 
	[purchase_invoice_account_number] varchar(8000) NULL, 
	[purchase_invoice_file_number] varchar(8000) NULL, 
	[purchase_invoice_industry_code] varchar(24) NULL, 
	[purchase_invoice_closed] datetime2(6) NULL, 
	[valid_from] datetime2(6) NULL, 
	[valid_to] datetime2(6) NULL, 
	[is_current] int NOT NULL
);