CREATE TABLE [cds].[purchase_order_dynamics] (

	[tkey_purchase_order] bigint NULL, 
	[bkey_purchase_order_source] varchar(8000) NULL, 
	[bkey_purchase_order] varchar(8000) NULL, 
	[bkey_source] varchar(8) NOT NULL, 
	[purchase_order_payment_schedule] varchar(8000) NULL, 
	[purchase_order_payment] varchar(8000) NULL, 
	[purchase_order_dct_destination] varchar(8000) NULL, 
	[purchase_order_ecs_contract_status] bigint NULL, 
	[purchase_order_risk_trading_book_id] varchar(8000) NULL, 
	[purchase_order_created_date_time] datetime2(6) NULL, 
	[purchase_order_company] varchar(8000) NULL, 
	[purchase_order_partition] bigint NULL, 
	[purchase_order_order_account] varchar(8000) NULL, 
	[purchase_order_requester] bigint NULL, 
	[purchase_order_risk_trader] bigint NULL, 
	[purchase_order_worker_purchase_placer] bigint NULL, 
	[purchase_order_purchase_state] bigint NULL, 
	[purchase_order_ccs_closing_status] bigint NULL, 
	[purchase_order_ecs_trade_type] bigint NULL, 
	[purchase_order_purchase_type] bigint NULL, 
	[purchase_order_invoice_account] varchar(8000) NULL, 
	[purchase_order_accounting_date] datetime2(6) NULL, 
	[purchase_order_invoice_date] datetime2(6) NULL, 
	[purchase_order_amount_trans_cur] decimal(38,6) NULL, 
	[purchase_order_amount_func_cur] decimal(38,6) NULL, 
	[purchase_order_amount_group_cur_oanda_eod] int NULL, 
	[purchase_order_group_cur_oanda_eod_rate] int NULL, 
	[purchase_order_func_cur_rate] decimal(38,6) NULL, 
	[purchase_order_internal_invoice_id] varchar(8000) NULL, 
	[purchase_order_local_product] varchar(8000) NULL, 
	[purchase_order_product] varchar(8000) NULL, 
	[purchase_order_transactional_currency_code] varchar(8000) NULL, 
	[purchase_order_group_currency_code] varchar(3) NOT NULL, 
	[purchase_order_functional_currency_code] varchar(30) NULL, 
	[purchase_order_line_number] decimal(38,16) NULL, 
	[purchase_order_incoterm] varchar(8000) NULL, 
	[purchase_order_origin_country] varchar(8000) NULL, 
	[purchase_order_destination_country] varchar(8000) NULL, 
	[purchase_order_quantity] decimal(38,6) NULL, 
	[purchase_order_quantity_mt] decimal(38,6) NULL, 
	[purchase_order_uom] varchar(8000) NULL, 
	[valid_from] datetime2(6) NULL, 
	[valid_to] datetime2(6) NULL, 
	[is_current] int NOT NULL
);