CREATE TABLE [cds].[purchase_invoice_line_cogs_dynamics_mst] (

	[tkey_purchase_invoice_line_cogs] bigint NULL, 
	[bkey_purchase_invoice_line_cogs_source] varchar(8000) NULL, 
	[bkey_purchase_invoice_line_cogs] varchar(8000) NULL, 
	[bkey_source] varchar(8) NULL, 
	[bkey_flow] varchar(3) NULL, 
	[purchase_invoice_line_cogs_file_number] varchar(8000) NULL, 
	[purchase_invoice_line_cogs_payment_schedule] varchar(8000) NULL, 
	[purchase_invoice_line_cogs_payment] varchar(8000) NULL, 
	[purchase_invoice_line_cogs_dct_destination] varchar(8000) NULL, 
	[purchase_invoice_line_cogs_ecs_contract_status] bigint NULL, 
	[purchase_invoice_line_cogs_risk_trading_book_id] varchar(8000) NULL, 
	[purchase_invoice_line_cogs_created_date_time] datetime2(6) NULL, 
	[purchase_invoice_line_cogs_company] varchar(8000) NULL, 
	[purchase_invoice_line_cogs_order_account] varchar(8000) NULL, 
	[purchase_invoice_line_cogs_requester] bigint NULL, 
	[purchase_invoice_line_cogs_risk_trader] bigint NULL, 
	[purchase_invoice_line_cogs_worker_purchase_placer] bigint NULL, 
	[purchase_invoice_line_cogs_purchase_state] varchar(30) NULL, 
	[purchase_invoice_line_cogs_ccs_closing_status] bigint NULL, 
	[purchase_invoice_line_cogs_ecs_trade_type] bigint NULL, 
	[purchase_invoice_line_cogs_purchase_type] bigint NULL, 
	[purchase_invoice_line_cogs_invoice_account] varchar(8000) NULL, 
	[purchase_invoice_line_cogs_accounting_date] datetime2(6) NULL, 
	[purchase_invoice_line_cogs_internal_invoice_id] varchar(8000) NULL, 
	[purchase_invoice_line_cogs_product] varchar(8000) NULL, 
	[purchase_invoice_line_cogs_purchase_id] varchar(8000) NULL, 
	[purchase_invoice_line_cogs_line_number] bigint NULL, 
	[purchase_invoice_line_cogs_incoterm] varchar(8000) NULL, 
	[purchase_invoice_line_cogs_origin_country] int NULL, 
	[purchase_invoice_line_cogs_destination_country] int NULL, 
	[purchase_invoice_line_cogs_adjusted_cogs_functional] decimal(38,6) NULL, 
	[purchase_invoice_line_cogs_adjusted_cogs_transactional] decimal(38,6) NULL, 
	[purchase_invoice_line_cogs_adjusted_cogs_group_conso_avg] numeric(38,6) NULL, 
	[purchase_invoice_line_cogs_cogs1_purchase_amount_functional] decimal(38,6) NULL, 
	[purchase_invoice_line_cogs_cogs1_purchase_amount_transactional] decimal(38,6) NULL, 
	[purchase_invoice_line_cogs_cogs1_purchase_amount_group_conso_avg] numeric(38,6) NULL, 
	[purchase_invoice_line_cogs_cogs1_freight_amount_functional] decimal(38,6) NULL, 
	[purchase_invoice_line_cogs_cogs1_freight_amount_transactional] decimal(38,6) NULL, 
	[purchase_invoice_line_cogs_cogs1_freight_amount_group_conso_avg] numeric(38,6) NULL, 
	[purchase_invoice_line_cogs_cogs1_other_amount_functional] decimal(38,6) NULL, 
	[purchase_invoice_line_cogs_cogs1_other_amount_transactional] decimal(38,6) NULL, 
	[purchase_invoice_line_cogs_cogs1_other_amount_group_conso_avg] numeric(38,6) NULL, 
	[valid_from] datetime2(6) NULL, 
	[valid_to] datetime2(6) NULL, 
	[is_current] int NOT NULL
);