CREATE TABLE [cds].[sales_invoice_line_cogs_stg] (

	[bkey_sales_invoice_line_cogs_source] varchar(8000) NULL, 
	[bkey_sales_invoice_line_cogs] varchar(8000) NULL, 
	[bkey_sales_invoice] varchar(8000) NULL, 
	[bkey_source] varchar(9) NOT NULL, 
	[sales_invoice_line_cogs_company] varchar(8000) NULL, 
	[sales_invoice_line_cogs_invoice_id] varchar(8000) NULL, 
	[sales_invoice_line_cogs_line_num] bigint NULL, 
	[sales_invoice_line_cogs_quantity] decimal(38,2) NULL, 
	[sales_invoice_line_cogs_uom] varchar(8000) NULL, 
	[sales_invoice_line_cogs_currency_code] varchar(8000) NULL, 
	[sales_invoice_line_product_id] varchar(8000) NULL, 
	[csv_sales_amount_m_local] decimal(38,4) NULL, 
	[csv_sales_amount_m_home] decimal(38,4) NULL, 
	[erp_sales_amount_m_local] int NULL, 
	[erp_sales_amount_m_home] int NULL, 
	[erp_cost_amount_posted] int NULL, 
	[erp_cogs1_purchase_amount_m_local] int NULL, 
	[erp_cogs1_purchase_amount_m_local_currency] int NULL, 
	[erp_cogs1_purchase_amount_m_home] int NULL, 
	[erp_cogs1_purchase_amount_m_group] int NULL, 
	[erp_cogs1_freight_amount_m_local] int NULL, 
	[erp_cogs1_freight_amount_m_local_currency] int NULL, 
	[erp_cogs1_freight_amount_m_home] int NULL, 
	[erp_cogs1_freight_amount_m_group] int NULL, 
	[erp_cogs1_other_amount_m_local] int NULL, 
	[erp_cogs1_other_amount_m_local_currency] int NULL, 
	[erp_cogs1_other_amount_m_home] int NULL, 
	[erp_cogs1_other_amount_m_group] int NULL, 
	[erp_cogs1_amount_m_local] int NULL, 
	[erp_cogs1_amount_m_local_currency] int NULL, 
	[erp_cogs1_amount_m_home] int NULL, 
	[erp_cogs1_amount_m_group] int NULL, 
	[erp_cogs2_internal_transport_amount_m_local] int NULL, 
	[erp_cogs2_internal_transport_amount_m_local_currency] int NULL, 
	[erp_cogs2_internal_transport_amount_m_home] int NULL, 
	[erp_cogs2_internal_transport_amount_m_group] int NULL, 
	[erp_cogs2_external_transport_amount_m_local] int NULL, 
	[erp_cogs2_external_transport_amount_m_local_currency] int NULL, 
	[erp_cogs2_external_transport_amount_m_home] int NULL, 
	[erp_cogs2_external_transport_amount_m_group] int NULL, 
	[erp_cogs2_other_amount_m_local] int NULL, 
	[erp_cogs2_other_amount_m_local_currency] int NULL, 
	[erp_cogs2_other_amount_m_home] int NULL, 
	[erp_cogs2_other_amount_m_group] int NULL, 
	[csv_cogs1_amount] decimal(38,4) NULL, 
	[csv_external_transport_amount] decimal(38,4) NULL, 
	[csv_internal_transport_amount] decimal(38,4) NULL, 
	[csv_other_cogs2_amount] decimal(38,4) NULL, 
	[csv_cogs2_amount] decimal(38,4) NULL, 
	[valid_from] datetime2(6) NULL, 
	[valid_to] datetime2(6) NULL, 
	[is_current] int NOT NULL
);