CREATE TABLE [cds].[sales_invoice_dynamics] (

	[bkey_sales_invoice_source] varchar(8000) NULL, 
	[bkey_sales_invoice] varchar(8000) NULL, 
	[bkey_source] varchar(8) NOT NULL, 
	[sales_invoice_id] varchar(8000) NULL, 
	[sales_invoice_customer_id] varchar(8000) NULL, 
	[sales_invoice_order_customer_id] varchar(8000) NULL, 
	[sales_invoice_company] varchar(8000) NULL, 
	[sales_invoice_transactional_currency_code] varchar(8000) NULL, 
	[sales_invoice_group_currency_code] varchar(3) NOT NULL, 
	[sales_invoice_functional_currency_code] varchar(30) NULL, 
	[sales_invoice_date] datetime2(6) NULL, 
	[sales_invoice_document_date] datetime2(6) NULL, 
	[sales_invoice_due_date] datetime2(6) NULL, 
	[sales_invoice_closure_date] datetime2(6) NULL, 
	[sales_invoice_amount_trans_cur] decimal(38,6) NULL, 
	[sales_invoice_amount_func_cur] decimal(38,6) NULL, 
	[sales_invoice_amount_group_cur_conso_eom] numeric(38,6) NULL, 
	[sales_invoice_amount_group_cur_conso_avg] numeric(38,6) NULL, 
	[sales_invoice_amount_group_cur_oanda_eod] int NULL, 
	[sales_invoice_open_amount_trans_cur] decimal(38,6) NULL, 
	[sales_invoice_open_amount_func_cur] decimal(38,6) NULL, 
	[sales_invoice_open_amount_group_cur_conso_eom] numeric(38,6) NULL, 
	[sales_invoice_open_amount_group_cur_conso_avg] numeric(38,6) NULL, 
	[sales_invoice_open_amount_group_cur_oanda_eod] int NULL, 
	[sales_invoice_settled_amount_trans_cur] decimal(38,6) NULL, 
	[sales_invoice_settled_amount_func_cur] decimal(38,6) NULL, 
	[sales_invoice_settled_amount_group_cur_conso_eom] numeric(38,6) NULL, 
	[sales_invoice_settled_amount_group_cur_conso_avg] numeric(38,6) NULL, 
	[sales_invoice_settled_amount_group_cur_oanda_eod] int NULL, 
	[sales_invoice_group_cur_conso_eom_rate] numeric(38,12) NULL, 
	[sales_invoice_group_cur_conso_avg_rate] numeric(38,12) NULL, 
	[sales_invoice_func_cur_rate] decimal(38,6) NULL, 
	[sales_invoice_name] varchar(8000) NULL, 
	[sales_invoice_customer_vat] varchar(8000) NULL, 
	[sales_invoice_destination_country] varchar(8000) NULL, 
	[sales_invoice_external_reference] varchar(8000) NULL, 
	[sales_invoice_payment_schedule] varchar(8000) NULL, 
	[sales_invoice_ledger_voucher] varchar(8000) NULL, 
	[sales_invoice_order_value] varchar(8000) NULL, 
	[sales_invoice_payment] varchar(8000) NULL, 
	[sales_invoice_txt] varchar(8000) NULL, 
	[sales_invoice_closed] datetime2(6) NULL, 
	[sales_invoice_payment_reference] varchar(8000) NULL, 
	[sales_invoice_paymtermid] varchar(8000) NULL, 
	[sales_invoice_procenvalue] varchar(8000) NULL, 
	[sales_invoice_coscenvalue] varchar(8000) NULL, 
	[sales_invoice_logistic_id] varchar(8000) NULL, 
	[sales_invoice_accrual_voucher] varchar(8000) NULL, 
	[sales_invoice_ledger_account] varchar(8000) NULL, 
	[sales_invoice_industry_code] varchar(8000) NULL, 
	[sales_invoice_invent_location] varchar(8000) NULL, 
	[sales_invoice_site_id] varchar(8000) NULL, 
	[sales_invoice_shipping_date] datetime2(6) NULL, 
	[valid_from] datetime2(6) NULL, 
	[valid_to] datetime2(6) NULL, 
	[is_current] int NOT NULL
);