CREATE TABLE [cds].[sales_plan_anaplan_dwh] (

	[tkey_sales_plan] varchar(8000) NOT NULL, 
	[sales_plan_budget_line_number] bigint NULL, 
	[tkey_sales_plan_source] varchar(8000) NOT NULL, 
	[sales_plan_category] varchar(8000) NULL, 
	[sales_plan_plan] varchar(8000) NULL, 
	[sales_plan_version] int NULL, 
	[sales_plan_company] varchar(8000) NULL, 
	[sales_plan_closure_date] datetime2(6) NULL, 
	[sales_plan_group_customer_id] varchar(8000) NULL, 
	[sales_plan_group_customer_name] varchar(8000) NULL, 
	[sales_plan_business_type] varchar(8000) NULL, 
	[sales_plan_group_product_id] varchar(8000) NULL, 
	[sales_plan_group_poduct_name] varchar(8000) NULL, 
	[sales_plan_uom] varchar(8000) NULL, 
	[sales_plan_quantity] float NULL, 
	[sales_plan_quantity_metric_ton] decimal(38,5) NULL, 
	[sales_plan_group_currency_total_amount] float NULL, 
	[sales_plan_home_currency_total_amount] float NULL, 
	[sales_plan_budget_currency_total_amount] decimal(38,5) NULL, 
	[sales_plan_group_currency_cogs1_amount] float NULL, 
	[sales_plan_home_currency_cogs1_amount] float NULL, 
	[sales_plan_budget_currency_cogs1_amount] decimal(38,5) NULL, 
	[sales_plan_group_currency_cogs2_amount] float NULL, 
	[sales_plan_home_currency_cogs2_amount] float NULL, 
	[sales_plan_budget_currency_cogs2_amount] decimal(38,5) NULL, 
	[sales_plan_home_currency] varchar(8000) NULL, 
	[sales_plan_plan_rate] float NULL, 
	[sales_plan_industry_type_code] varchar(8000) NULL, 
	[sales_plan_customer_code_cgk] varchar(8000) NULL, 
	[sales_plan_destination_country] varchar(8000) NULL, 
	[sales_plan_product_grouping_code] varchar(8000) NULL, 
	[sales_plan_product_code] varchar(8000) NULL, 
	[sales_plan_currency] varchar(8000) NULL
);