CREATE TABLE [cds].[sales_invoice_stg_ar] (

	[bkey_sales_invoice_source] varchar(8000) NULL, 
	[bkey_sales_invoice] varchar(8000) NULL, 
	[bkey_source] varchar(6) NOT NULL, 
	[sales_invoice_id] varchar(8000) NULL, 
	[sales_invoice_customer_id] varchar(8000) NULL, 
	[sales_invoice_order_customer_id] varchar(30) NULL, 
	[sales_invoice_company] varchar(8000) NULL, 
	[sales_invoice_transactional_currency_code] varchar(8000) NULL, 
	[sales_invoice_group_currency_code] varchar(3) NOT NULL, 
	[sales_invoice_functional_currency_code] int NULL, 
	[sales_invoice_date] varchar(8000) NULL, 
	[sales_invoice_document_date] int NULL, 
	[sales_invoice_due_date] varchar(8000) NULL, 
	[sales_invoice_closure_date] varchar(8000) NULL, 
	[sales_invoice_amount_trans_cur] decimal(38,2) NULL, 
	[sales_invoice_amount_func_cur] decimal(38,6) NULL, 
	[sales_invoice_amount_group_cur_conso_eom] numeric(38,6) NULL, 
	[sales_invoice_amount_group_cur_conso_avg] numeric(38,6) NULL, 
	[sales_invoice_amount_group_cur_oanda_eod] int NULL, 
	[sales_invoice_open_amount_trans_cur] decimal(38,2) NULL, 
	[sales_invoice_open_amount_func_cur] decimal(38,2) NULL, 
	[sales_invoice_open_amount_group_cur_conso_eom] numeric(38,6) NULL, 
	[sales_invoice_open_amount_group_cur_conso_avg] numeric(38,6) NULL, 
	[sales_invoice_open_amount_group_cur_oanda_eod] int NULL, 
	[sales_invoice_settled_amount_trans_cur] decimal(38,2) NULL, 
	[sales_invoice_settled_amount_func_cur] decimal(38,2) NULL, 
	[sales_invoice_settled_amount_group_cur_conso_eom] numeric(38,6) NULL, 
	[sales_invoice_settled_amount_group_cur_conso_avg] numeric(38,6) NULL, 
	[sales_invoice_settled_amount_group_cur_oanda_eod] int NULL, 
	[sales_invoice_group_cur_conso_eom_rate] numeric(38,12) NULL, 
	[sales_invoice_group_cur_conso_avg_rate] numeric(38,12) NULL, 
	[sales_invoice_func_cur_rate] decimal(38,6) NULL, 
	[sales_invoice_name] int NULL, 
	[sales_invoice_customer_vat] varchar(8000) NULL, 
	[sales_invoice_destination_country] int NULL, 
	[sales_invoice_external_reference] int NULL, 
	[sales_invoice_payment_schedule] varchar(8000) NULL, 
	[sales_invoice_ledger_voucher] int NULL, 
	[sales_invoice_order_value] int NULL, 
	[sales_invoice_payment] int NULL, 
	[sales_invoice_txt] int NULL, 
	[sales_invoice_closed] int NULL, 
	[sales_invoice_payment_reference] int NULL, 
	[sales_invoice_paymtermid] int NULL, 
	[sales_invoice_procenvalue] int NULL, 
	[sales_invoice_coscenvalue] int NULL, 
	[sales_invoice_logistic_id] int NULL, 
	[sales_invoice_ledger_account] int NULL, 
	[sales_invoice_industry_code] int NULL, 
	[sales_invoice_invent_location] int NULL, 
	[sales_invoice_site_id] int NULL, 
	[valid_from] datetime2(6) NULL, 
	[valid_to] datetime2(6) NULL, 
	[is_current] int NOT NULL
);