CREATE TABLE [cds].[sales_plan_dwh] (

	[bkey_sales_plan] varchar(8000) NOT NULL, 
	[bkey_sales_plan_source] varchar(8000) NOT NULL, 
	[sales_plan_budget_line_number] bigint NULL, 
	[bkey_source] varchar(3) NOT NULL, 
	[sales_plan_category] varchar(8000) NULL, 
	[sales_plan_plan] varchar(8000) NULL, 
	[sales_plan_version] int NULL, 
	[sales_plan_company] varchar(8000) NULL, 
	[sales_plan_closure_date] datetime2(6) NULL, 
	[sales_plan_global_customer_code] varchar(8000) NULL, 
	[sales_plan_customer_id] varchar(8000) NULL, 
	[sales_plan_customer_name] varchar(8000) NULL, 
	[sales_plan_business_type] varchar(8000) NULL, 
	[sales_plan_product_global_code] varchar(8000) NULL, 
	[sales_plan_poduct_global_name] varchar(8000) NULL, 
	[sales_plan_uom] varchar(8000) NULL, 
	[sales_plan_quantity] float NULL, 
	[sales_plan_quantity_metric_ton] decimal(38,5) NULL, 
	[sales_plan_home_currency] varchar(8000) NULL, 
	[sales_plan_plan_rate] float NULL, 
	[sales_plan_industry_type_code] varchar(8000) NULL, 
	[sales_plan_customer_code_cgk] varchar(8000) NULL, 
	[sales_plan_destination_country] varchar(8000) NULL, 
	[sales_plan_currency] varchar(8000) NULL, 
	[sales_plan_total_amount_trans_cur] int NULL, 
	[sales_plan_total_amount_func_cur] float NULL, 
	[sales_plan_total_amount_group_cur] float NULL, 
	[sales_plan_cogs1_amount_trans_cur] int NULL, 
	[sales_plan_cogs1_amount_func_cur] float NULL, 
	[sales_plan_cogs1_amount_group_cur] float NULL, 
	[sales_plan_cogs2_amount_trans_cur] int NULL, 
	[sales_plan_cogs2_amount_func_cur] float NULL, 
	[sales_plan_cogs2_amount_group_cur] float NULL, 
	[valid_from] varchar(8000) NULL, 
	[valid_to] varchar(8000) NULL, 
	[is_current] int NOT NULL
);