CREATE TABLE [cds].[sales_invoice_line_cogs_dynamics_mits] (

	[tkey_sales_invoice_line_cogs] bigint NULL, 
	[bkey_sales_invoice_line_cogs_source] varchar(8000) NULL, 
	[bkey_sales_invoice_line_cogs] varchar(8000) NULL, 
	[bkey_sales_invoice] varchar(8000) NULL, 
	[bkey_source] varchar(8) NOT NULL, 
	[bkey_flow] varchar(4) NOT NULL, 
	[sales_invoice_line_cogs_invoice_id] varchar(8000) NULL, 
	[sales_invoice_line_cogs_line_number] decimal(38,16) NULL, 
	[sales_invoice_line_cogs_product_id] varchar(8000) NULL, 
	[sales_invoice_line_cogs_product_global_code] varchar(8000) NULL, 
	[sales_invoice_line_cogs_customer_id] varchar(8000) NULL, 
	[sales_invoice_line_cogs_file_number] varchar(8000) NULL, 
	[sales_invoice_line_cogs_quantity] decimal(38,6) NULL, 
	[sales_invoice_line_cogs_quantity_mt] decimal(38,6) NULL, 
	[sales_invoice_line_cogs_uom] varchar(8000) NULL, 
	[sales_invoice_line_cogs_company] varchar(8000) NULL, 
	[sales_invoice_line_cogs_invoice_currency_code] varchar(8000) NULL, 
	[sales_invoice_line_cogs_business_unit] int NULL, 
	[sales_invoice_line_amount_func_cur] decimal(38,6) NULL, 
	[sales_invoice_line_amount_trans_cur] decimal(38,6) NULL, 
	[sales_invoice_line_amount_group_cur_conso_avg] numeric(38,6) NULL, 
	[cogs1_costofgood_amount_func_cur] decimal(38,6) NULL, 
	[cogs1_costofgood_amount_trans_cur] decimal(38,6) NULL, 
	[cogs1_costofgood_amount_conso_avg] numeric(38,6) NULL, 
	[cogs1_freight_amount_funccur] decimal(38,6) NULL, 
	[sfreight_amount_transcur] decimal(38,6) NULL, 
	[cogs1_freight_amount_groupcur_conso_avg] numeric(38,6) NULL, 
	[cogs1_other_amount_funccur] decimal(38,6) NULL, 
	[cogs1_other_amount_transcur] decimal(38,6) NULL, 
	[cogs1_other_amount_groupcur_conso_avg] numeric(38,6) NULL, 
	[total_cogs1_amount_func_cur] decimal(38,6) NULL, 
	[total_cogs1_amount_trans_cur] decimal(38,6) NULL, 
	[total_cogs1_amount_group_conso_avg] numeric(38,6) NULL, 
	[cogs2_transport_internal_amount_func_cur] decimal(38,6) NULL, 
	[cogs2_transport_internal_amount_trans_cur] decimal(38,6) NULL, 
	[cogs2_transport_internal_amount_group_conso_avg] numeric(38,6) NULL, 
	[cogs2_transport_external_amount_func_cur] decimal(38,6) NULL, 
	[cogs2_transport_external_amount_trans_cur] decimal(38,6) NULL, 
	[cogs2_transport_external_amount_group_conso_avg] numeric(38,6) NULL, 
	[cogs2_other_amount_func_cur] decimal(38,6) NULL, 
	[cogs2_other_amount_trans_cur] decimal(38,6) NULL, 
	[cogs2_other_amount_group_conso_avg] numeric(38,6) NULL, 
	[total_cogs2_amount_func_cur] decimal(38,6) NULL, 
	[total_cogs2_amount_trans_cur] decimal(38,6) NULL, 
	[total_cogs2_amount_group_conso_avg] numeric(38,6) NULL, 
	[valid_from] datetime2(6) NULL, 
	[valid_to] datetime2(6) NULL, 
	[is_current] int NOT NULL
);