CREATE TABLE [cds].[stock_stg] (

	[bkey_stock_source] varchar(8000) NOT NULL, 
	[bkey_stock] varchar(8000) NOT NULL, 
	[bkey_source] varchar(9) NOT NULL, 
	[stock_company] varchar(8000) NULL, 
	[stock_customer_id] int NULL, 
	[stock_currency] varchar(8000) NULL, 
	[stock_closure_date] varchar(8000) NULL, 
	[stock_entry_date] varchar(8000) NULL, 
	[stock_warehouse_name] varchar(8000) NULL, 
	[stock_invent_location_id] int NULL, 
	[stock_site_id] int NULL, 
	[stock_lot_number] varchar(8000) NULL, 
	[stock_product_code] varchar(8000) NULL, 
	[stock_product_id] varchar(8000) NULL, 
	[stock_quantity] varchar(8000) NULL, 
	[stock_quantity_mt] decimal(38,20) NULL, 
	[stock_uom] varchar(8000) NULL, 
	[stock_amount_func_cur] varchar(8000) NULL, 
	[stock_amount_group_conso_eom] numeric(38,6) NULL, 
	[stock_amount_group_oanda_eod] int NULL, 
	[stock_committed] int NOT NULL, 
	[stock_in_transit] int NOT NULL, 
	[stock_file_name] varchar(8000) NULL, 
	[valid_from] datetime2(6) NULL, 
	[valid_to] datetime2(6) NULL, 
	[is_current] int NOT NULL
);