CREATE TABLE [dds_finance].[dim_company] (

	[tkey_company] bigint NULL, 
	[bkey_company] varchar(255) NULL, 
	[company_code] varchar(255) NULL, 
	[company_name] varchar(255) NULL, 
	[consolidation_method] varchar(255) NULL, 
	[company_active_flag] bit NULL, 
	[company_local_currency] varchar(255) NULL, 
	[company_home_currency] varchar(255) NULL, 
	[company_home_currency_description] varchar(255) NULL, 
	[company_country_code] varchar(255) NULL, 
	[company_group_percentage] decimal(5,2) NULL, 
	[company_minor_percentage] decimal(5,2) NULL, 
	[company_group_control_percentage] decimal(5,2) NULL, 
	[company_tree_level_1] varchar(255) NULL, 
	[company_tree_level_2] varchar(255) NULL, 
	[company_min_reporting_period] int NULL, 
	[company_country_name] varchar(255) NULL, 
	[company_country_sort] int NULL, 
	[company_iso_code] varchar(255) NULL, 
	[company_region_level_1] varchar(255) NULL, 
	[company_region_level_1_sort] int NULL, 
	[company_region_level_2] varchar(255) NULL, 
	[company_region_level_2_sort] int NULL, 
	[valid_from] datetime2(6) NULL, 
	[valid_to] datetime2(6) NULL, 
	[is_current] bit NULL
);