CREATE TABLE [dds_finance].[dim_customer] (

	[tkey_customer] bigint NULL, 
	[bkey_customer] varchar(255) NULL, 
	[bkey_customer_global] varchar(255) NULL, 
	[customer_code] varchar(255) NULL, 
	[customer_global_code] varchar(255) NULL, 
	[customer_id] varchar(8000) NULL, 
	[customer_legal_number] varchar(8000) NULL, 
	[customer_name] varchar(8000) NULL, 
	[customer_company] varchar(8000) NULL, 
	[customer_country_code] varchar(8000) NULL, 
	[customer_address] varchar(8000) NULL, 
	[customer_city] varchar(8000) NULL, 
	[customer_zip_code] varchar(8000) NULL, 
	[customer_industry] varchar(8000) NULL, 
	[customer_industry_description] varchar(8000) NULL, 
	[customer_affiliate] varchar(3) NOT NULL, 
	[customer_group] varchar(8000) NULL, 
	[customer_group_description] varchar(8000) NULL, 
	[customer_multinational_legal_number] varchar(8000) NULL, 
	[customer_multinational_name] varchar(8000) NULL, 
	[customer_gkam] int NULL, 
	[customer_country_name] varchar(255) NULL, 
	[customer_country_sort] int NULL, 
	[customer_iso_code] varchar(255) NULL, 
	[customer_region_level_1] varchar(255) NULL, 
	[customer_region_level_1_sort] int NULL, 
	[customer_region_level_2] varchar(255) NULL, 
	[customer_region_level_2_sort] int NULL, 
	[valid_from] datetime2(6) NULL, 
	[valid_to] datetime2(6) NULL, 
	[is_current] bit NULL
);