CREATE TABLE [dds_finance].[fact_purchasing] (

	[tkey_invoice_date] int NULL, 
	[tkey_closure_date] int NULL, 
	[tkey_product] bigint NULL, 
	[tkey_supplier] bigint NULL, 
	[tkey_currency_transactional] bigint NULL, 
	[tkey_currency_group] bigint NULL, 
	[tkey_currency_functional] bigint NULL, 
	[tkey_company] bigint NULL, 
	[tkey_incoterm] bigint NULL, 
	[tkey_payment_term] bigint NULL, 
	[tkey_country_origin] bigint NULL, 
	[tkey_country_destination] bigint NULL, 
	[file_number] varchar(8000) NULL, 
	[lot_number] int NULL, 
	[invoice_supplier_id] varchar(8000) NULL, 
	[local_supplier_id] int NULL, 
	[local_product] varchar(8000) NULL, 
	[internal_invoice_id] varchar(8000) NULL, 
	[line_number] decimal(38,16) NULL, 
	[invoice_amount_transactional_currency] decimal(38,6) NULL, 
	[invoice_amount_functional_currency] decimal(38,6) NULL, 
	[invoice_amount_group_currency_oanda_eod] int NULL, 
	[invoice_closing_rate] numeric(38,25) NULL, 
	[invoice_average_month_rate] numeric(38,25) NULL, 
	[quantity] decimal(38,6) NULL, 
	[quantity_mt] decimal(38,6) NULL, 
	[unit_of_measure] varchar(8000) NULL
);