CREATE TABLE [dds_finance].[fact_invoices_payable] (

	[tkey_invoice_date] int NULL, 
	[tkey_due_date] int NULL, 
	[tkey_snapshot_date] int NULL, 
	[tkey_company] bigint NULL, 
	[tkey_supplier] bigint NULL, 
	[tkey_currency] bigint NULL, 
	[tkey_payment_term] bigint NULL, 
	[tkey_customer_industry_invoice] bigint NULL, 
	[tkey_age_group] bigint NULL, 
	[AP_invoice_amount_transactional_currency] decimal(38,2) NULL, 
	[AP_invoice_amount_functional_currency] decimal(38,6) NULL, 
	[AP_invoice_amount_group_conso_EOM_currency] numeric(38,6) NULL, 
	[AP_invoice_amount_group_OANDA_spot_currency] int NULL, 
	[AP_open_amount_transactional_currency] decimal(38,2) NULL, 
	[AP_open_amount_functional_currency] decimal(38,2) NULL, 
	[AP_open_amount_group_conso_EOM_currency] numeric(38,6) NULL, 
	[AP_open_amount_group_OANDA_spot_currency] int NULL, 
	[AP_settled_amount_transactional_currency] decimal(38,2) NULL, 
	[AP_settled_amount_functional_currency] decimal(38,2) NULL, 
	[AP_settled_amount_group_conso_EOM_currency] numeric(38,6) NULL, 
	[AP_settled_amount_group_OANDA_spot_currency] int NULL, 
	[invoice_number] varchar(50) NULL, 
	[legal_number] varchar(50) NULL, 
	[settlement_date] datetime2(6) NULL, 
	[status] varchar(14) NOT NULL, 
	[payment_progress_percentage] decimal(38,6) NULL, 
	[snapshot_granularity] varchar(7) NOT NULL, 
	[source] varchar(8) NOT NULL
);