CREATE TABLE [dds_finance].[fact_stock] (

	[tkey_entry_date] int NULL, 
	[tkey_snapshot_date] int NULL, 
	[tkey_company] bigint NULL, 
	[tkey_customer] bigint NULL, 
	[tkey_currency] bigint NULL, 
	[tkey_stock_age_group] bigint NULL, 
	[tkey_product] bigint NULL, 
	[tkey_product_global] bigint NULL, 
	[tkey_site] bigint NULL, 
	[stock_committed] bit NULL, 
	[stock_in_transit] bit NULL, 
	[stock_quantity] decimal(18,4) NULL, 
	[stock_quantity_mt] decimal(18,4) NULL, 
	[stock_amount_functional_currency] decimal(18,4) NULL, 
	[stock_amount_group_conso_EOM_currency] decimal(18,4) NULL, 
	[stock_amount_group_OANDA_spot_currency] decimal(18,4) NULL, 
	[product_in_stock_amount_functional_currency] decimal(38,4) NULL, 
	[product_in_stock_amount_group_conso_EOM_currency] decimal(38,4) NULL, 
	[product_in_stock_amount_group_OANDA_spot_currency] decimal(38,4) NULL, 
	[stock_sales_last_3_months_transactional_currency] decimal(38,4) NULL, 
	[stock_sales_last_3_months_functional_currency] decimal(38,4) NULL, 
	[stock_sales_last_3_months_group_conso_AVG_currency] decimal(38,4) NULL, 
	[stock_sales_last_3_months_group_OANDA_spot_currency] decimal(38,4) NULL, 
	[stock_lot_number] varchar(255) NULL, 
	[stock_uom] varchar(255) NULL, 
	[stock_warehouse_name] varchar(255) NULL, 
	[snapshot_granularity] varchar(7) NOT NULL, 
	[source] varchar(9) NOT NULL
);