CREATE TABLE [dds_finance].[fact_purchasing_landing_costs] (

	[tkey_created_date] int NULL, 
	[tkey_accounting_date] int NULL, 
	[tkey_product] bigint NULL, 
	[tkey_company] bigint NULL, 
	[tkey_supplier] bigint NULL, 
	[tkey_incoterm] bigint NULL, 
	[tkey_payment_term] bigint NULL, 
	[tkey_country_origin] bigint NULL, 
	[tkey_country_destination] bigint NULL, 
	[file_number] varchar(8000) NULL, 
	[lot_number] int NULL, 
	[invoice_supplier_id] varchar(8000) NULL, 
	[local_supplier_id] int NULL, 
	[local_product] int NULL, 
	[internal_invoice_id] varchar(8000) NULL, 
	[purchase_id] varchar(8000) NULL, 
	[line_number] bigint NULL, 
	[adjusted_cogs_functional] decimal(38,6) NULL, 
	[adjusted_cogs_transactional] decimal(38,6) NULL, 
	[adjusted_cogs_group] decimal(38,6) NULL, 
	[cogs1_purchase_amount_functional] decimal(38,6) NULL, 
	[cogs1_purchase_amount_transactional] decimal(38,6) NULL, 
	[cogs1_purchase_amount_group] decimal(38,6) NULL, 
	[cogs1_freight_amount_functional] decimal(38,6) NULL, 
	[cogs1_freight_amount_transactional] decimal(38,6) NULL, 
	[cogs1_freight_amount_group] decimal(38,6) NULL, 
	[cogs1_other_amount_functional] decimal(38,6) NULL, 
	[cogs1_other_amount_transactional] decimal(38,6) NULL, 
	[cogs1_other_amount_group] decimal(38,6) NULL
);