CREATE TABLE [dds_finance].[fact_invoices_receivable] (

	[tkey_invoice_date] int NULL, 
	[tkey_due_date] int NULL, 
	[tkey_snapshot_date] int NULL, 
	[tkey_company] bigint NULL, 
	[tkey_customer] bigint NULL, 
	[tkey_currency] bigint NULL, 
	[tkey_payment_term] bigint NULL, 
	[tkey_customer_industry_invoice] bigint NULL, 
	[tkey_age_group] bigint NULL, 
	[AR_invoice_amount_transactional_currency] decimal(36,6) NULL, 
	[AR_invoice_amount_functional_currency] decimal(36,6) NULL, 
	[AR_invoice_amount_group_conso_EOM_currency] decimal(36,6) NULL, 
	[AR_invoice_amount_group_OANDA_spot_currency] decimal(36,6) NULL, 
	[AR_open_amount_transactional_currency] decimal(36,6) NULL, 
	[AR_open_amount_functional_currency] decimal(36,6) NULL, 
	[AR_open_amount_group_conso_EOM_currency] decimal(36,6) NULL, 
	[AR_open_amount_group_OANDA_spot_currency] decimal(36,6) NULL, 
	[AR_settled_amount_transactional_currency] decimal(38,6) NULL, 
	[AR_settled_amount_functional_currency] decimal(38,6) NULL, 
	[AR_settled_amount_group_conso_EOM_currency] decimal(38,6) NULL, 
	[AR_settled_amount_group_OANDA_spot_currency] decimal(38,6) NULL, 
	[AR_sales_last_3_weeks_transactional_currency] decimal(18,0) NULL, 
	[AR_sales_last_3_weeks_functional_currency] decimal(18,0) NULL, 
	[AR_sales_last_3_weeks_group_conso_AVG_currency] decimal(18,0) NULL, 
	[AR_sales_last_3_weeks_group_OANDA_spot_currency] decimal(18,0) NULL, 
	[invoice_number] varchar(50) NULL, 
	[legal_number] varchar(50) NULL, 
	[settlement_date] datetime2(6) NULL, 
	[status] varchar(14) NOT NULL, 
	[payment_progress_percentage] decimal(38,6) NULL, 
	[snapshot_granularity] varchar(7) NOT NULL, 
	[source] varchar(9) NULL
);