CREATE TABLE [TD035C2].[TD035C2__ODS] (

	[ConsolidatedAmountID] bigint NULL, 
	[ConsoID] int NULL, 
	[CompanyID] int NULL, 
	[JournalTypeID] int NULL, 
	[JournalEntry] bigint NULL, 
	[JournalSequence] int NULL, 
	[AccountID] int NULL, 
	[PartnerCompanyID] int NULL, 
	[CurrCode] varchar(8000) NULL, 
	[Amount] decimal(24,6) NULL, 
	[TransactionCurrCode] varchar(8000) NULL, 
	[TransactionAmount] decimal(24,6) NULL, 
	[MinorityFlag] bit NULL, 
	[ODSKey] varchar(61) NULL, 
	[ODSVersion] varchar(8000) NULL, 
	[ODSHash] varchar(8000) NULL, 
	[ODSRecordStatus] varchar(8000) NULL, 
	[ODSActive] varchar(8000) NULL, 
	[ODSDeleted] varchar(8000) NULL, 
	[ODSModifiedOn] varchar(8000) NULL, 
	[ODSModifiedBy] varchar(8000) NULL, 
	[ODSIngestionDate] varchar(8000) NULL, 
	[ODSStartDate] varchar(8000) NULL, 
	[ODSEndDate] varchar(8000) NULL
);