CREATE TABLE [mim].[rv_sat_sales_invoice_line] (

	[bkey_sales_invoice_line_source] varchar(100) NULL, 
	[bkey_sales_invoice] varchar(100) NULL, 
	[bkey_source] varchar(30) NULL, 
	[sales_invoice_id] varchar(8000) NULL, 
	[sales_invoice_line_invoice_line_num] decimal(18,0) NULL, 
	[sales_invoice_line_product_id] varchar(8000) NULL, 
	[sales_invoice_line_product_name] varchar(8000) NULL, 
	[sales_invoice_line_quantity] decimal(38,6) NULL, 
	[sales_invoice_line_quantity_mt] decimal(38,6) NULL, 
	[sales_invoice_line_uom] varchar(8000) NULL, 
	[sales_invoice_line_amount_trans_cur] decimal(18,4) NULL, 
	[sales_invoice_line_amount_func_cur] decimal(18,4) NULL, 
	[sales_invoice_line_amount_group_cur_conso_avg] decimal(18,4) NULL, 
	[sales_invoice_line_amount_group_cur_oanda_eod] decimal(18,4) NULL, 
	[sales_invoice_line_group_cur_conso_avg_rate] numeric(38,12) NULL, 
	[sales_invoice_line_func_cur_rate] decimal(38,6) NULL, 
	[sales_invoice_line_company] varchar(8000) NULL, 
	[sales_invoice_line_transactional_currency_code] varchar(8000) NULL, 
	[sales_invoice_line_group_currency_code] varchar(3) NOT NULL, 
	[sales_invoice_line_functional_currency_code] varchar(30) NULL, 
	[sales_invoice_line_ledger_voucher] varchar(8000) NULL, 
	[sales_invoice_line_business_unit] varchar(30) NULL, 
	[sales_invoice_line_product_global_code] varchar(100) NULL, 
	[valid_from] datetime2(6) NULL, 
	[valid_to] datetime2(6) NULL, 
	[is_current] int NOT NULL
);