CREATE TABLE [mim].[rv_sat_purchase_order_line] (

	[bkey_purchase_order_line_source] varchar(69) NULL, 
	[bkey_source] varchar(8) NOT NULL, 
	[purchase_order_line_purchase_id] varchar(8000) NULL, 
	[purchase_order_line_line_number] bigint NULL, 
	[purchase_order_line_company] varchar(8000) NULL, 
	[purchase_order_line_name] varchar(8000) NULL, 
	[purchase_order_line_delivery_term] varchar(8000) NULL, 
	[purchase_order_line_quantity_ordered] decimal(38,6) NULL, 
	[purchase_order_line_purchase_unit] varchar(8000) NULL, 
	[purchase_order_line_amount_trans_cur] decimal(38,6) NULL, 
	[purchase_order_line_amount_func_cur] int NULL, 
	[purchase_order_line_amount_group_cur_oanda_spot] int NULL, 
	[purchase_order_line_group_cur_oanda_rate] int NULL, 
	[purchase_order_line_func_cur_rate] int NULL, 
	[purchase_order_line_transactional_currency_code] varchar(8000) NULL, 
	[purchase_order_line_group_currency_code] varchar(3) NOT NULL, 
	[purchase_order_line_functional_currency_code] varchar(30) NULL, 
	[purchase_order_line_price_unit] decimal(38,12) NULL, 
	[purchase_order_line_delivery_mode] varchar(8000) NULL, 
	[purchase_order_line_created_date_time] datetime2(6) NULL, 
	[purchase_order_line_purchase_status] bigint NULL, 
	[purchase_order_line_inventory_dimension_id] varchar(8000) NULL, 
	[purchase_order_line_partition] bigint NULL, 
	[purchase_order_line_lgs_logistic_file_id] varchar(8000) NULL, 
	[purchase_order_line_product_id] varchar(8000) NULL, 
	[purchase_order_line_purchase_price] decimal(38,6) NULL, 
	[purchase_order_line_vendor_account] varchar(8000) NULL, 
	[purchase_order_line_purchase_quantity] decimal(38,6) NULL, 
	[purchase_order_line_purchase_quantity_mt] decimal(38,6) NULL, 
	[purchase_order_line_uom] varchar(8000) NULL, 
	[valid_from] datetime2(6) NULL, 
	[valid_to] datetime2(6) NULL, 
	[is_current] int NOT NULL
);