CREATE TABLE [mim].[rv_sat_purchase_invoice_line] (

	[bkey_purchase_invoice_line_source] varchar(8000) NULL, 
	[bkey_purchase_invoice] varchar(8000) NULL, 
	[bkey_source] varchar(8) NOT NULL, 
	[purchase_invoice_line_number] decimal(38,16) NULL, 
	[purchase_invoice_line_description] varchar(8000) NULL, 
	[purchase_invoice_line_quantity] decimal(38,6) NULL, 
	[purchase_invoice_line_product_id] varchar(8000) NULL, 
	[purchase_invoice_line_amount_trans_cur] decimal(38,6) NULL, 
	[purchase_invoice_line_amount_func_cur] decimal(38,6) NULL, 
	[purchase_invoice_line_amount_group_cur_conso_avg] numeric(38,6) NULL, 
	[purchase_invoice_line_amount_group_cur_oanda_eod] int NULL, 
	[purchase_invoice_line_group_cur_oanda_eod_rate] int NULL, 
	[purchase_invoice_line_group_cur_conso_avg_rate] numeric(38,12) NULL, 
	[purchase_invoice_line_func_cur_rate] decimal(38,6) NULL, 
	[purchase_invoice_line_transactional_currency_code] varchar(8000) NULL, 
	[purchase_invoice_line_group_currency_code] varchar(3) NOT NULL, 
	[purchase_invoice_line_functional_currency_code] varchar(30) NULL, 
	[purchase_invoice_line_company] varchar(8000) NULL, 
	[purchase_invoice_line_UOM] varchar(8000) NULL, 
	[purchase_invoice_line_ledger_voucher] varchar(8000) NULL, 
	[purchase_invoice_line_payment_term_id] varchar(8000) NULL, 
	[purchase_invoice_line_closed] datetime2(6) NULL, 
	[purchase_invoice_line_tax_amount] decimal(38,6) NULL, 
	[valid_from] datetime2(6) NULL, 
	[valid_to] datetime2(6) NULL, 
	[is_current] int NOT NULL
);