CREATE TABLE [mim].[rv_sat_invoice_payable] (

	[bkey_invoice_payable_source] varchar(8000) NULL, 
	[bkey_source] varchar(6) NOT NULL, 
	[invoice_payable_invoice_id] varchar(8000) NULL, 
	[invoice_payable_supplier_id] varchar(8000) NULL, 
	[invoice_payable_company] varchar(8000) NULL, 
	[invoice_payable_local_currency_code] varchar(8000) NULL, 
	[invoice_payable_invoice_date] datetime2(6) NULL, 
	[invoice_payable_due_date] datetime2(6) NULL, 
	[invoice_payable_closure_date] datetime2(6) NULL, 
	[invoice_payable_amount_trans_cur] decimal(38,2) NULL, 
	[invoice_payable_amount_func_cur] decimal(38,6) NULL, 
	[invoice_payable_amount_group_cur_conso_eom] numeric(38,6) NULL, 
	[invoice_payable_amount_group_cur_conso_avg] numeric(38,6) NULL, 
	[invoice_payable_amount_group_cur_oanda_eod] int NULL, 
	[invoice_payable_open_amount_trans_cur] decimal(38,2) NULL, 
	[invoice_payable_open_amount_func_cur] decimal(38,2) NULL, 
	[invoice_payable_open_amount_group_cur_conso_eom] numeric(38,6) NULL, 
	[invoice_payable_open_amount_group_cur_conso_avg] numeric(38,6) NULL, 
	[invoice_payable_open_amount_group_cur_oanda_eod] int NULL, 
	[invoice_payable_settled_amount_trans_cur] decimal(38,2) NULL, 
	[invoice_payable_settled_amount_func_cur] decimal(38,2) NULL, 
	[invoice_payable_settled_amount_group_cur_conso_eom] numeric(38,6) NULL, 
	[invoice_payable_settled_amount_group_cur_conso_avg] numeric(38,6) NULL, 
	[invoice_payable_settled_amount_group_cur_oanda_eod] int NULL, 
	[invoice_payable_payment_schedule] varchar(8000) NULL, 
	[invoice_payable_file_name] varchar(8000) NULL, 
	[valid_from] datetime2(6) NULL, 
	[valid_to] datetime2(6) NULL, 
	[is_current] int NOT NULL
);