CREATE TABLE [mim].[rv_sat_sales_invoice] (

	[bkey_sales_invoice_source] varchar(8000) NULL, 
	[bkey_sales_invoice] varchar(100) NULL, 
	[bkey_source] varchar(9) NOT NULL, 
	[sales_invoice_id] varchar(50) NULL, 
	[sales_invoice_customer_id] varchar(50) NULL, 
	[sales_invoice_order_customer_id] varchar(50) NULL, 
	[sales_invoice_company] varchar(50) NULL, 
	[sales_invoice_transactional_currency_code] varchar(50) NULL, 
	[sales_invoice_group_currency_code] varchar(50) NULL, 
	[sales_invoice_functional_currency_code] varchar(50) NULL, 
	[sales_invoice_date] datetime2(6) NULL, 
	[sales_invoice_document_date] datetime2(6) NULL, 
	[sales_invoice_due_date] datetime2(6) NULL, 
	[sales_invoice_closure_date] datetime2(6) NULL, 
	[sales_invoice_amount_trans_cur] decimal(36,6) NULL, 
	[sales_invoice_amount_func_cur] decimal(36,6) NULL, 
	[sales_invoice_amount_group_cur_conso_eom] decimal(36,6) NULL, 
	[sales_invoice_amount_group_cur_conso_avg] decimal(36,6) NULL, 
	[sales_invoice_amount_group_cur_oanda_eod] decimal(36,6) NULL, 
	[sales_invoice_open_amount_trans_cur] decimal(36,6) NULL, 
	[sales_invoice_open_amount_func_cur] decimal(36,6) NULL, 
	[sales_invoice_open_amount_group_cur_conso_eom] decimal(36,6) NULL, 
	[sales_invoice_open_amount_group_cur_conso_avg] decimal(36,6) NULL, 
	[sales_invoice_open_amount_group_cur_oanda_eod] decimal(36,6) NULL, 
	[sales_invoice_settled_amount_trans_cur] decimal(36,6) NULL, 
	[sales_invoice_settled_amount_func_cur] decimal(36,6) NULL, 
	[sales_invoice_settled_amount_group_cur_conso_eom] decimal(36,6) NULL, 
	[sales_invoice_settled_amount_group_cur_conso_avg] decimal(36,6) NULL, 
	[sales_invoice_settled_amount_group_cur_oanda_eod] decimal(36,6) NULL, 
	[sales_invoice_group_cur_conso_eom_rate] decimal(36,6) NULL, 
	[sales_invoice_group_cur_conso_avg_rate] decimal(36,6) NULL, 
	[sales_invoice_func_cur_rate] decimal(36,6) NULL, 
	[sales_invoice_name] varchar(50) NULL, 
	[sales_invoice_customer_vat] varchar(50) NULL, 
	[sales_invoice_destination_country] varchar(50) NULL, 
	[sales_invoice_external_reference] varchar(50) NULL, 
	[sales_invoice_payment_schedule] varchar(50) NULL, 
	[sales_invoice_ledger_voucher] varchar(50) NULL, 
	[sales_invoice_order_value] varchar(50) NULL, 
	[sales_invoice_payment] varchar(50) NULL, 
	[sales_invoice_txt] varchar(50) NULL, 
	[sales_invoice_closed] varchar(50) NULL, 
	[sales_invoice_payment_reference] varchar(50) NULL, 
	[sales_invoice_paymtermid] varchar(50) NULL, 
	[sales_invoice_procenvalue] varchar(30) NULL, 
	[sales_invoice_coscenvalue] varchar(30) NULL, 
	[sales_invoice_logistic_id] varchar(30) NULL, 
	[sales_invoice_ledger_account] varchar(30) NULL, 
	[sales_invoice_industry_code] varchar(30) NULL, 
	[sales_invoice_invent_location] varchar(30) NULL, 
	[sales_invoice_site_id] varchar(30) NULL, 
	[sales_invoice_shipping_date] datetime2(6) NULL, 
	[valid_from] datetime2(6) NULL, 
	[valid_to] datetime2(6) NULL, 
	[is_current] int NOT NULL
);