CREATE TABLE [mim].[rv_sat_purchase_invoice_cogs] (

	[tkey_purchase_invoice_cogs] varchar(49) NULL, 
	[bkey_purchase_invoice_line_source] varchar(8000) NULL, 
	[bkey_purchase_invoice_line] varchar(8000) NULL, 
	[bkey_purchase_order_source] varchar(8000) NULL, 
	[bkey_purchase_order] varchar(8000) NULL, 
	[bkey_source] varchar(8) NOT NULL, 
	[purchase_invoice_cogs_line_number] decimal(38,16) NULL, 
	[purchase_invoice_cogs_company] varchar(8000) NULL, 
	[purchase_invoice_cogs_product] varchar(8000) NULL, 
	[purchase_invoice_cogs_line_description] varchar(8000) NULL, 
	[purchase_invoice_cogs_quantity] decimal(38,6) NULL, 
	[purchase_invoice_cogs_unit_of_measure] varchar(8000) NULL, 
	[purchase_invoice_cogs_currency_code] varchar(8000) NULL, 
	[purchase_invoice_cogs_line_amount] decimal(38,6) NULL, 
	[purchase_invoice_cogs_line_amount_mst] decimal(38,6) NULL, 
	[purchase_invoice_cogs_ledger_account] varchar(8000) NULL, 
	[erp_cogs1_purchasing_home_currency_amount] decimal(38,6) NULL, 
	[erp_cogs1_purchasing_local_currency_amount] decimal(38,6) NULL, 
	[erp_cogs1_purchasing_local_currency] varchar(8000) NULL, 
	[erp_cogs1_purchasing_group_currency_amount] decimal(38,6) NULL, 
	[erp_cogs1_freight_home_currency_amount] decimal(38,6) NULL, 
	[erp_cogs1_freight_local_currency_amount] decimal(38,6) NULL, 
	[erp_cogs1_freight_local_currency] varchar(8000) NULL, 
	[erp_cogs1_freight_group_currency_amount] decimal(38,6) NULL, 
	[erp_cogs1_other_home_currency_amount] decimal(38,6) NULL, 
	[erp_cogs1_other_local_currency_amount] decimal(38,6) NULL, 
	[erp_cogs1_other_local_currency] varchar(8000) NULL, 
	[erp_cogs1_other_group_currency_amount] decimal(38,6) NULL, 
	[purchase_invoice_cogs_ledger_account_code] varchar(8000) NULL, 
	[purchase_invoice_cogs_description] varchar(8000) NULL, 
	[valid_from] datetime2(6) NULL, 
	[valid_to] datetime2(6) NULL, 
	[is_current] int NOT NULL
);